server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8082  #sentinel地址
        port: 8719
#对Feign的支持
feign:
  sentinel:
    enabled: true
